name: Trigger - PR merged to the Main branch
run-name: Trigger - PR merged to the Main branch
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/pages_deploy.yml
    secrets: inherit
